const { withAppBuildGradle } = require('@expo/config-plugins');
const os = require('os');
const path = require('path');

/**
 * Config plugin that configures Android release signing from a local keystore
 * properties file at ~/.handy/happy-android.keystore.properties.
 *
 * The file format:
 *   storeFile=/Users/<you>/.handy/happy-release.keystore
 *   storePassword=<password>
 *   keyAlias=happy
 *   keyPassword=<password>
 *
 * This plugin:
 *   1. Injects Groovy code to load the properties file before the android{} block
 *   2. Adds a 'release' signingConfig reading from those properties
 *   3. Switches the release buildType to use signingConfig.release
 *
 * The properties file is never committed to git and only needs to exist on
 * machines that perform production builds.
 */
module.exports = function withAndroidSigning(config) {
    return withAppBuildGradle(config, (config) => {
        let contents = config.modResults.contents;

        // ── 1. Inject keystore properties loader before the android{} block ──
        const LOADER_BLOCK = `
// Load production keystore credentials from ~/.handy/happy-android.keystore.properties
// This file is NOT committed to version control.
def keystorePropertiesFile = new File(System.getProperty('user.home') + '/.handy/happy-android.keystore.properties')
def keystoreProperties = new Properties()
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}

`;

        if (!contents.includes('happy-android.keystore.properties')) {
            // Insert immediately before the android { block
            contents = contents.replace('android {', LOADER_BLOCK + 'android {');
        }

        // ── 2. Add 'release' signingConfig to the signingConfigs block ──
        const RELEASE_SIGNING = `
        release {
            if (keystorePropertiesFile.exists()) {
                storeFile file(keystoreProperties['storeFile'])
                storePassword keystoreProperties['storePassword']
                keyAlias keystoreProperties['keyAlias']
                keyPassword keystoreProperties['keyPassword']
            }
        }`;

        if (!contents.includes("signingConfig signingConfigs.release")) {
            // Add release signingConfig after the debug one
            contents = contents.replace(
                /signingConfigs \{([^}]+)\}/s,
                (match) => {
                    // Only add if not already present
                    if (match.includes('release {')) return match;
                    return match.slice(0, -1) + RELEASE_SIGNING + '\n    }';
                }
            );
        }

        // ── 3. Switch release buildType to use signingConfigs.release ──
        // The default generated by Expo uses signingConfigs.debug for release.
        contents = contents.replace(
            /(\s*\/\/\s*Caution!.*?\n.*?see.*?\n\s*)signingConfig signingConfigs\.debug/s,
            '$1signingConfig signingConfigs.release'
        );

        config.modResults.contents = contents;
        return config;
    });
};
