const { withGradleProperties } = require('@expo/config-plugins');

/**
 * Config plugin that raises the Android Gradle daemon JVM heap.
 *
 * Background: the default `org.gradle.jvmargs=-Xmx2048m` (2GB heap) generated by
 * expo prebuild is not enough to complete this app's R8/D8 dex merge
 * (:app:mergeExtDexRelease), which fails with
 * `java.lang.OutOfMemoryError: Java heap space`.
 *
 * Because android/ is regenerated by `expo prebuild --clean`, hand-editing
 * android/gradle.properties does not persist. This plugin re-applies the heap
 * setting on every prebuild via the withGradleProperties mod.
 *
 * Sets -Xmx4096m and -XX:MaxMetaspaceSize=1024m.
 */
const HEAP = '-Xmx4096m';
const METASPACE = '-XX:MaxMetaspaceSize=1024m';
const JVM_ARGS = `${HEAP} ${METASPACE}`;

module.exports = function withAndroidGradleHeap(config) {
    return withGradleProperties(config, (config) => {
        const properties = config.modResults;

        const existing = properties.find(
            (item) => item.type === 'property' && item.key === 'org.gradle.jvmargs'
        );

        if (existing) {
            existing.value = JVM_ARGS;
        } else {
            properties.push({
                type: 'property',
                key: 'org.gradle.jvmargs',
                value: JVM_ARGS,
            });
        }

        console.log(`[withAndroidGradleHeap] Set org.gradle.jvmargs=${JVM_ARGS}`);
        return config;
    });
};
